INSERT INTO books (author, title, isbn, is_available) VALUES ('J.K.Rowling', 'Harry Potter and the Philosopher''s Stone', '9780747532743', true);
INSERT INTO books (author, title, isbn, is_available) VALUES ('J.K.Rowling', 'Harry Potter and the Philosopher''s Stone', '9780747532743', false);
INSERT INTO books (author, title, isbn, is_available) VALUES ('J.K.Rowling', 'Harry Potter and the Chamber of Secrets', '9780747538486', true);
INSERT INTO books (author, title, isbn, is_available) VALUES ('J.K.Rowling', 'Harry Potter and the Prisoner of Azkaban', '9780747546290', true);
INSERT INTO books (author, title, isbn, is_available) VALUES ('J.K.Rowling', 'Harry Potter and the Goblet of Fire', '9780747550990', false);
INSERT INTO books (author, title, isbn, is_available) VALUES ('J.R.R.Tolkien', 'The lord of the Rings', '9780007136582', false);
INSERT INTO books (author, title, isbn, is_available) VALUES ('J.R.R.Tolkien', 'The lord of the Rings', '9780007136582', true);
INSERT INTO books (author, title, isbn, is_available) VALUES ('J.R.R.Tolkien', 'The lord of the Rings', '9780007136582', true);
INSERT INTO books (author, title, isbn, is_available) VALUES ('J.K.Rowling', 'Harry Potter and the Order of the Phoenix', '9780747561071', false);
INSERT INTO books (author, title, isbn, is_available) VALUES ('Douglas Adams', 'The Salmon of Doubt(Hitchhiker''s Guide to the Galaxy)', '9780345460950', true);
INSERT INTO books (author, title, isbn, is_available) VALUES ('J.K.Rowling', 'Harry Potter And the Half-Blood Prince', '9780747584681', true);
INSERT INTO books (author, title, isbn, is_available) VALUES ('J.K.Rowling', 'Harry Potter and the Deathly Hallows', '9780545010221', false);
INSERT INTO books (author, title, isbn, is_available) VALUES ('J.K.Rowling', 'Harry Potter and the Deathly Hallows', '9780545010221', false);
INSERT INTO books (author, title, isbn, is_available) VALUES ('Douglas Adams', 'Mostly Harmless(Hitchhiker''s Guide to the Galaxy)', '9780747532743', true);
INSERT INTO books (author, title, isbn, is_available) VALUES ('Douglas Adams', 'Mostly Harmless(Hitchhiker''s Guide to the Galaxy)', '9780747532743', true);
INSERT INTO books (author, title, isbn, is_available) VALUES ('Douglas Adams', 'The Hitchhiker''s Guide to the Galaxy', '9780804191852', true);
